spring.application.name=mini-shop-backend
spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/minishop
spring.datasource.username=postgres
spring.datasource.password=Muhammad2323.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
